AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  vpcDoesNotExists:
    Fn::Equals:
    - Ref: VPCExists
    - false
Mappings:
  RegionMap:
    us-east-1:
      AZ1: us-east-1a
      AZ2: us-east-1b
      AZ3: us-east-1c
    us-west-1:
      AZ1: us-west-1a
      AZ2: us-west-1b
      AZ3: us-west-1c
    us-west-2:
      AZ1: us-west-2a
      AZ2: us-west-2b
      AZ3: us-west-2c
Outputs:
  VPC:
    Description: Main VPC
    Export:
      Name:
        Fn::Join:
        - ''
        - - VPC
          - Ref: Tenant
    Value:
      Ref: VPC
Parameters:
  APPSN1Cidr:
    Default: 192.168.14.0/24
    Type: String
  APPSN2Cidr:
    Default: 192.168.15.0/24
    Type: String
  APPSN3Cidr:
    Default: 192.168.16.0/24
    Type: String
  CidrBlock:
    Default: 192.168.0.0/16
    Type: String
  DBInstance:
    Default: dbinstance
    Type: String
  DBIsMultiZone:
    AllowedValues:
    - true
    - false
    Default: false
    Type: String
  DBMasterPassword:
    Default: replaceMe
    Type: String
  DBMasterUser:
    Default: root
    Type: String
  DBName:
    Default: dmdb
    Type: String
  DBSN1Cidr:
    Default: 192.168.34.0/24
    Type: String
  DBSN2Cidr:
    Default: 192.168.35.0/24
    Type: String
  EFSN1Cidr:
    Default: 192.168.24.0/24
    Type: String
  EFSN2Cidr:
    Default: 192.168.25.0/24
    Type: String
  EFSN3Cidr:
    Default: 192.168.26.0/24
    Type: String
  MCSN1Cidr:
    Default: 192.168.44.0/24
    Type: String
  Tenant:
    Default: DEV
    Description: Tenant name
    Type: String
  VPCExists:
    AllowedValues:
    - true
    - false
    Default: false
    Type: String
  WSSN1Cidr:
    Default: 192.168.4.0/24
    Type: String
  WSSN2Cidr:
    Default: 192.168.5.0/24
    Type: String
  WSSN3Cidr:
    Default: 192.168.6.0/24
    Type: String
Resources:
  APPSubnet1:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ1
      CidrBlock:
        Ref: APPSN1Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - APPSN1
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  APPSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: APPSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation
  APPSubnet2:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ2
      CidrBlock:
        Ref: APPSN2Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - APPSN2
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  APPSubnet2RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: APPSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation
  APPSubnet3:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ3
      CidrBlock:
        Ref: APPSN3Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - APPSN3
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  APPSubnet3RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: APPSubnet3
    Type: AWS::EC2::SubnetRouteTableAssociation
  AttachGateway:
    Condition: vpcDoesNotExists
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
    Type: AWS::EC2::VPCGatewayAttachment
  DBSubnet1:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ1
      CidrBlock:
        Ref: DBSN1Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - DBSN1
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  DBSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: DBSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation
  DBSubnet2:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ2
      CidrBlock:
        Ref: DBSN2Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - DBSN2
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  DBSubnet2RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: DBSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation
  ECSubnetGroup:
    Properties:
      Description: Cache Subnet Group
      SubnetIds:
      - Ref: MCSubnet1
    Type: AWS::ElastiCache::SubnetGroup
  EFSubnet1:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ1
      CidrBlock:
        Ref: EFSN1Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - EFSN1
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  EFSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: EFSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation
  EFSubnet2:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ2
      CidrBlock:
        Ref: EFSN2Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - EFSN2
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  EFSubnet2RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: EFSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation
  EFSubnet3:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ3
      CidrBlock:
        Ref: EFSN3Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - EFSN3
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  EFSubnet3RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: EFSubnet3
    Type: AWS::EC2::SubnetRouteTableAssociation
  ElasticacheCluster:
    Properties:
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName:
        Ref: ECSubnetGroup
      Engine: memcached
      NumCacheNodes: 1
      VpcSecurityGroupIds:
      - Fn::GetAtt:
        - ElasticacheSecurityGroup
        - GroupId
    Type: AWS::ElastiCache::CacheCluster
  ElasticacheSecurityGroup:
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
      - FromPort: '11211'
        IpProtocol: tcp
        ToPort: '11211'
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup
  FileSystem:
    Properties:
      FileSystemTags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - EFS
            - Ref: Tenant
      - Key: Tenant
        Value:
          Ref: Tenant
      PerformanceMode: generalPurpose
    Type: AWS::EFS::FileSystem
  InternetGateway:
    Condition: vpcDoesNotExists
    Properties:
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - IG
            - Ref: Tenant
      - Key: Tenant
        Value:
          Ref: Tenant
    Type: AWS::EC2::InternetGateway
  MCSubnet1:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ1
      CidrBlock:
        Ref: MCSN1Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - MCSN1
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  MCSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: MCSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation
  MountTarget1:
    Properties:
      FileSystemId:
        Ref: FileSystem
      SecurityGroups:
      - Ref: MountTargetSecurityGroup
      SubnetId:
        Ref: EFSubnet1
    Type: AWS::EFS::MountTarget
  MountTarget2:
    Properties:
      FileSystemId:
        Ref: FileSystem
      SecurityGroups:
      - Ref: MountTargetSecurityGroup
      SubnetId:
        Ref: EFSubnet2
    Type: AWS::EFS::MountTarget
  MountTarget3:
    Properties:
      FileSystemId:
        Ref: FileSystem
      SecurityGroups:
      - Ref: MountTargetSecurityGroup
      SubnetId:
        Ref: EFSubnet3
    Type: AWS::EFS::MountTarget
  MountTargetSecurityGroup:
    Properties:
      GroupDescription: Security group for mount target
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '2049'
        IpProtocol: tcp
        ToPort: '2049'
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup
  PrivateRouteTable:
    Properties:
      Tags:
      - Key: Name
        Value: MD_PVT_ROUTE
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - RTB
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::RouteTable
  PublicRoute:
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable
    Type: AWS::EC2::Route
  PublicRouteTable:
    Properties:
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - PRT
            - Ref: Tenant
      - Key: Tenant
        Value:
          Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::RouteTable
  RDSDBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DB Subnet Group.
      SubnetIds:
      - Ref: DBSubnet1
      - Ref: DBSubnet2
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - RDSSNG
            - Ref: Tenant
      - Key: Tenant
        Value:
          Ref: Tenant
    Type: AWS::RDS::DBSubnetGroup
  RDSDEVDB:
    Properties:
      AllocatedStorage: '5'
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier:
        Ref: DBInstance
      DBName:
        Ref: DBName
      DBSubnetGroupName:
        Ref: RDSDBSubnetGroup
      Engine: MySQL
      MasterUserPassword:
        Ref: DBMasterPassword
      MasterUsername:
        Ref: DBMasterUser
      MultiAZ:
        Ref: DBIsMultiZone
      PubliclyAccessible: false
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - RDS
            - Ref: Tenant
      - Key: Tenant
        Value:
          Ref: Tenant
    Type: AWS::RDS::DBInstance
  VPC:
    Properties:
      CidrBlock:
        Ref: CidrBlock
      Tags:
      - Key: Name
        Value:
          Ref: Tenant
    Type: AWS::EC2::VPC
  WSSubnet1:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ1
      CidrBlock:
        Ref: WSSN1Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - WSSN1
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  WSSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: WSSubnet1
    Type: AWS::EC2::SubnetRouteTableAssociation
  WSSubnet2:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ2
      CidrBlock:
        Ref: WSSN2Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - WSSN2
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  WSSubnet2RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: WSSubnet2
    Type: AWS::EC2::SubnetRouteTableAssociation
  WSSubnet3:
    Properties:
      AvailabilityZone:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AZ3
      CidrBlock:
        Ref: WSSN3Cidr
      Tags:
      - Key: Tenant
        Value:
          Ref: Tenant
      - Key: Name
        Value:
          Fn::Join:
          - ''
          - - WSSN3
            - Ref: Tenant
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  WSSubnet3RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: WSSubnet3
    Type: AWS::EC2::SubnetRouteTableAssociation
